//! Guest-side helpers for HomeCmdr WASM plugins.
//!
//! This crate provides:
//!
//! - [`DeviceKind`] — strongly-typed device kind values.
//! - JSON attribute builder functions — build the `attributes_json` string
//!   passed to `DeviceUpdate` without writing raw JSON by hand.
//! - [`hc_log!`] — a logging macro that delegates to the host-provided
//!   `host_log` interface generated by `wit_bindgen::generate!` in the
//!   calling plugin crate.
//!
//! # Usage
//!
//! Add to your plugin's `Cargo.toml` (adjust the relative path as needed):
//!
//! ```toml
//! [dependencies]
//! homecmdr-plugin-sdk = { path = "../../crates/plugin-sdk" }
//! ```
//!
//! Your `lib.rs` still generates its own WIT bindings and implements `Guest`:
//!
//! ```rust,ignore
//! wit_bindgen::generate!({ world: "adapter", path: "wit/homecmdr-plugin.wit" });
//!
//! use homecmdr_plugin_sdk::{DeviceKind, measurement_attributes};
//!
//! impl Guest for MyPlugin {
//!     fn poll() -> Result<Vec<DeviceUpdate>, String> {
//!         let attrs = measurement_attributes("temperature_outdoor", 21.5, "celsius");
//!         Ok(vec![DeviceUpdate {
//!             vendor_id: "temperature_outdoor".into(),
//!             kind: DeviceKind::Sensor.as_str().into(),
//!             attributes_json: attrs,
//!         }])
//!     }
//! }
//! export!(MyPlugin);
//! ```

// ---------------------------------------------------------------------------
// DeviceKind
// ---------------------------------------------------------------------------

/// The device kind reported in [`DeviceUpdate::kind`].
///
/// Use [`DeviceKind::as_str`] to obtain the string value expected by the host.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DeviceKind {
    /// A read-only measured value (temperature, humidity, etc.).
    Sensor,
    /// A controllable lighting device.
    Light,
    /// A generic on/off device.
    Switch,
    /// A logical (non-physical) device.
    Virtual,
}

impl DeviceKind {
    /// The string value expected by the HomeCmdr host for `DeviceUpdate::kind`.
    pub fn as_str(self) -> &'static str {
        match self {
            DeviceKind::Sensor => "sensor",
            DeviceKind::Light => "light",
            DeviceKind::Switch => "switch",
            DeviceKind::Virtual => "virtual",
        }
    }
}

// ---------------------------------------------------------------------------
// JSON attribute helpers
// ---------------------------------------------------------------------------

/// Build a measurement attributes JSON string.
///
/// Produces `{"<key>": {"value": <v>, "unit": "<unit>"}}`.
///
/// Use this for numeric sensor values that carry a physical unit:
/// temperatures, pressures, humidity percentages, wind speeds, etc.
///
/// # Examples
///
/// ```
/// let json = homecmdr_plugin_sdk::measurement_attributes("temperature_outdoor", 21.5, "celsius");
/// assert!(json.contains("\"temperature_outdoor\""));
/// assert!(json.contains("\"celsius\""));
/// ```
pub fn measurement_attributes(key: &str, value: f64, unit: &str) -> String {
    serde_json::json!({ key: { "value": value, "unit": unit } }).to_string()
}

/// Build an accumulation attributes JSON string.
///
/// Produces `{"<key>": {"value": <v>, "unit": "<unit>", "period": "<period>"}}`.
///
/// Use this for values that accumulate over a time window, e.g. rainfall per hour.
///
/// # Examples
///
/// ```
/// let json = homecmdr_plugin_sdk::accumulation_attributes("rainfall", 2.4, "mm", "hour");
/// assert!(json.contains("\"hour\""));
/// ```
pub fn accumulation_attributes(key: &str, value: f64, unit: &str, period: &str) -> String {
    serde_json::json!({ key: { "value": value, "unit": unit, "period": period } }).to_string()
}

/// Build an integer scalar attributes JSON string.
///
/// Produces `{"<key>": <value>}`.
///
/// Use this for dimensionless integer values such as `cloud_coverage` or
/// `wind_direction` where no physical unit applies.
///
/// # Examples
///
/// ```
/// let json = homecmdr_plugin_sdk::integer_attributes("cloud_coverage", 75);
/// assert_eq!(json, r#"{"cloud_coverage":75}"#);
/// ```
pub fn integer_attributes(key: &str, value: i64) -> String {
    serde_json::json!({ key: value }).to_string()
}

/// Build a float scalar attributes JSON string.
///
/// Produces `{"<key>": <value>}`.
///
/// Use this for dimensionless floating-point values such as `uv_index`.
///
/// # Examples
///
/// ```
/// let json = homecmdr_plugin_sdk::float_attributes("uv_index", 3.2);
/// assert!(json.contains("\"uv_index\""));
/// ```
pub fn float_attributes(key: &str, value: f64) -> String {
    serde_json::json!({ key: value }).to_string()
}

/// Build a text attributes JSON string.
///
/// Produces `{"<key>": "<value>"}`.
///
/// Use this for string-valued attributes such as `weather_condition`.
///
/// # Examples
///
/// ```
/// let json = homecmdr_plugin_sdk::text_attributes("weather_condition", "Clear sky");
/// assert_eq!(json, r#"{"weather_condition":"Clear sky"}"#);
/// ```
pub fn text_attributes(key: &str, value: &str) -> String {
    serde_json::json!({ key: value }).to_string()
}

/// Build a boolean attributes JSON string.
///
/// Produces `{"<key>": <true|false>}`.
///
/// Use this for boolean attributes such as `custom.open_meteo.is_day`.
///
/// # Examples
///
/// ```
/// let json = homecmdr_plugin_sdk::bool_attributes("custom.open_meteo.is_day", true);
/// assert_eq!(json, r#"{"custom.open_meteo.is_day":true}"#);
/// ```
pub fn bool_attributes(key: &str, value: bool) -> String {
    serde_json::json!({ key: value }).to_string()
}

/// Build an arbitrary map attributes JSON string from key-value pairs.
///
/// Each pair is `(key, value_json)` where `value_json` is an already-serialised
/// JSON fragment (use `serde_json::to_string` or a literal like `"42"` / `"\"text\""`).
///
/// Useful when you need to combine multiple fields into a single
/// `attributes_json` map (the `DeviceUpdate::attributes_json` field must be a
/// JSON object, not an array of objects).
///
/// # Examples
///
/// ```
/// let json = homecmdr_plugin_sdk::multi_attributes(&[
///     ("power", "true"),
///     ("brightness", "80"),
/// ]);
/// assert!(json.contains("\"power\":true"));
/// assert!(json.contains("\"brightness\":80"));
/// ```
pub fn multi_attributes(pairs: &[(&str, &str)]) -> String {
    let mut map = serde_json::Map::new();
    for (k, v) in pairs {
        let val: serde_json::Value =
            serde_json::from_str(v).unwrap_or(serde_json::Value::String(v.to_string()));
        map.insert(k.to_string(), val);
    }
    serde_json::Value::Object(map).to_string()
}

// ---------------------------------------------------------------------------
// Logging macro
// ---------------------------------------------------------------------------

/// Log a message through the host-provided `host_log` interface.
///
/// This macro expands to a call to `homecmdr::plugin::host_log::log`, which
/// is the function generated by `wit_bindgen::generate!` in the **calling**
/// plugin crate.  It therefore only compiles inside a plugin crate that has
/// already run the WIT code-generator.
///
/// # Syntax
///
/// ```rust,ignore
/// hc_log!(info, "adapter started for lat={} lon={}", lat, lon);
/// hc_log!(warn, "retrying after error: {}", err);
/// hc_log!(error, "fatal: {}", msg);
/// hc_log!(debug, "raw response: {}", body);
/// hc_log!(trace, "tick");
/// ```
///
/// Supported levels: `error`, `warn`, `info`, `debug`, `trace`.
#[macro_export]
macro_rules! hc_log {
    (error, $($arg:tt)*) => {
        homecmdr::plugin::host_log::log("error", &::std::format!($($arg)*))
    };
    (warn, $($arg:tt)*) => {
        homecmdr::plugin::host_log::log("warn", &::std::format!($($arg)*))
    };
    (info, $($arg:tt)*) => {
        homecmdr::plugin::host_log::log("info", &::std::format!($($arg)*))
    };
    (debug, $($arg:tt)*) => {
        homecmdr::plugin::host_log::log("debug", &::std::format!($($arg)*))
    };
    (trace, $($arg:tt)*) => {
        homecmdr::plugin::host_log::log("trace", &::std::format!($($arg)*))
    };
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn measurement_attributes_shape() {
        let j = measurement_attributes("temperature_outdoor", 21.5, "celsius");
        let v: serde_json::Value = serde_json::from_str(&j).unwrap();
        assert_eq!(v["temperature_outdoor"]["value"], 21.5);
        assert_eq!(v["temperature_outdoor"]["unit"], "celsius");
    }

    #[test]
    fn accumulation_attributes_shape() {
        let j = accumulation_attributes("rainfall", 2.4, "mm", "hour");
        let v: serde_json::Value = serde_json::from_str(&j).unwrap();
        assert_eq!(v["rainfall"]["period"], "hour");
    }

    #[test]
    fn integer_attributes_shape() {
        let j = integer_attributes("cloud_coverage", 75);
        let v: serde_json::Value = serde_json::from_str(&j).unwrap();
        assert_eq!(v["cloud_coverage"], 75);
    }

    #[test]
    fn float_attributes_shape() {
        let j = float_attributes("uv_index", 3.2);
        let v: serde_json::Value = serde_json::from_str(&j).unwrap();
        assert_eq!(v["uv_index"], 3.2);
    }

    #[test]
    fn text_attributes_shape() {
        let j = text_attributes("weather_condition", "Clear sky");
        let v: serde_json::Value = serde_json::from_str(&j).unwrap();
        assert_eq!(v["weather_condition"], "Clear sky");
    }

    #[test]
    fn bool_attributes_shape() {
        let j = bool_attributes("custom.open_meteo.is_day", true);
        let v: serde_json::Value = serde_json::from_str(&j).unwrap();
        assert_eq!(v["custom.open_meteo.is_day"], true);
    }

    #[test]
    fn multi_attributes_shape() {
        let j = multi_attributes(&[("power", "true"), ("brightness", "80")]);
        let v: serde_json::Value = serde_json::from_str(&j).unwrap();
        assert_eq!(v["power"], true);
        assert_eq!(v["brightness"], 80);
    }

    #[test]
    fn multi_attributes_string_fallback() {
        // A non-JSON-parseable raw string is stored as a JSON string value.
        let j = multi_attributes(&[("label", "hello world")]);
        let v: serde_json::Value = serde_json::from_str(&j).unwrap();
        assert_eq!(v["label"], "hello world");
    }

    #[test]
    fn device_kind_as_str() {
        assert_eq!(DeviceKind::Sensor.as_str(), "sensor");
        assert_eq!(DeviceKind::Light.as_str(), "light");
        assert_eq!(DeviceKind::Switch.as_str(), "switch");
        assert_eq!(DeviceKind::Virtual.as_str(), "virtual");
    }
}
